# ------ root_path/dataset_name ------
root_path: ~


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False


# ------ Basic Config ------
dataset: 'imagenet'
shots: 16
backbone: 'RN50'
lr: 0.0001
augment_epoch: 10
train_epoch: 5
